spring:
  application:
    name: accounts
  cache:
    redis:
      timeToLiveMillis: 5000

logging:
  level:
    root: INFO

github:
  api:
    url: https://api.github.com

feign:
  client:
    config:
      github:
        connectTimeoutMillis: 5000 # 5 seconds connection timeout
        readTimeoutMillis: 10000   # 10 seconds read timeout